# Build webapp and publish artifact

name: webstore-build

on:
  workflow_dispatch:



jobs:
  build:
    name: 'Build and Publish .NET Web App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: restore
        run: dotnet restore

      - run: dotnet build --configuration Release
        name: build 

      - run: dotnet publish --configuration Release -o ./webstore
        name: publish 


